variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "-B -fae"
  MAVEN_NO_PACKAGING: "-Ddisable.distribution.packaging=true"
  MAVEN_NO_TESTS: "-DskipTests=true"

stages:
- testing
- release
- post-release

cache:
  key: "$CI_PROJECT_NAME"
  paths:
  - .m2/repository

before_script:
- mkdir -p .m2/repository

after_script:
# Never cache itself.
- rm -rf .m2/repository/net/morimekta/providence/ || true

.test: &test
  stage: testing
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /\[silent-ignore\]/
    - $CI_COMMIT_MESSAGE =~ /\[maven-release-plugin\]/
  script:
  - mvn ${MAVEN_CLI_OPTS} ${MAVEN_NO_PACKAGING} verify -Plib,cli
  - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { OFMT = "%.2f"; print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' */target/site/jacoco-ut/jacoco.csv
  coverage: /([0-9]{1,3}[.][0-9][0-9]) % covered/

test:jdk8:
  <<: *test
  image:
    name: maven:3.5-jdk-8-alpine
    entrypoint: ["/bin/bash", "-c"]
  after_script:
    # Never cache itself.
    - rm -rf .m2/repository/net/morimekta/providence/ || true
    - apk add --no-cache git
    - |
      # Report coverage only chen a java file has changed.
      NUM_JAVA=$(git diff origin/master..HEAD --name-only | grep '.java$' | wc -l)
      if [[ $NUM_JAVA -gt 0 ]]
      then
        echo "Sending jacoco coverage report to codecov.io"
        curl -s https://codecov.io/bash | bash -s
      fi

test:jdk11:
  <<: *test
  image: maven:3.5-jdk-11-slim

packaging:
  stage: release
  image: maven:3.5-jdk-8-alpine
  only:
  - tags
  before_script:
  - apk update
  - apk add --no-cache git rpm
  - mkdir -p .m2/repository
  script:
  - mvn ${MAVEN_CLI_OPTS} ${MAVEN_NO_TESTS} package -Plib,cli
  - mv providence-tools/target/providence-tools-*.tar.gz .
  - mv providence-tools/target/providence-*.deb .
  - mv providence-tools/target/rpm/providence/RPMS/noarch/providence-*.noarch.rpm .
  artifacts:
    paths:
    - providence-tools-*.tar.gz
    - providence-*.deb
    - providence-*.noarch.rpm

pages:
  image: ruby:2.5
  cache:
    key: "vendor-$CI_PROJECT_NAME"
    paths:
    - docs/vendor/
  stage: post-release
  before_script:
  - cd docs
  - bundle install --path vendor
  script:
  - bundle exec jekyll build -d public
  - mv public ..
  artifacts:
    paths:
    - public
  only:
  - master
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /\[silent-ignore\]/
    - $CI_COMMIT_MESSAGE =~ /\[maven-release-plugin\]/      
