dist: trusty
language: java
jdk:
  - openjdk8
  - oraclejdk8
branches:
  only:
    - master
script: "mvn verify -Plib,cli,it"
before_install:
  - sudo apt-get -y install rpm
  - unset _JAVA_OPTIONS
after_success:
  - bash <(curl -s https://codecov.io/bash)
