language: java
jdk:
  # - openjdk8 # add when openjdk8 is also supported
  - oraclejdk8
branches:
  only:
  - master
before_install:
- sudo apt-get -y install rpm
after_success:
- bash <(curl -s https://codecov.io/bash)
