/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package net.morimekta.test.thrift.serialization.common;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Value implements org.apache.thrift.TEnum {
  FIRST(1),
  SECOND(2),
  THIRD(3),
  FOURTH(5),
  FIFTH(8),
  SIXTH(13),
  SEVENTH(21),
  EIGHTH(34),
  NINTH(55),
  TENTH(89),
  ELEVENTH(144),
  TWELWETH(233),
  /**
   * @Deprecated
   */
  THIRTEENTH(377),
  FOURTEENTH(610),
  FIFTEENTH(987),
  SIXTEENTH(1597),
  SEVENTEENTH(2584),
  EIGHTEENTH(4181),
  NINTEENTH(6765),
  TWENTIETH(10946);

  private final int value;

  private Value(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Value findByValue(int value) { 
    switch (value) {
      case 1:
        return FIRST;
      case 2:
        return SECOND;
      case 3:
        return THIRD;
      case 5:
        return FOURTH;
      case 8:
        return FIFTH;
      case 13:
        return SIXTH;
      case 21:
        return SEVENTH;
      case 34:
        return EIGHTH;
      case 55:
        return NINTH;
      case 89:
        return TENTH;
      case 144:
        return ELEVENTH;
      case 233:
        return TWELWETH;
      case 377:
        return THIRTEENTH;
      case 610:
        return FOURTEENTH;
      case 987:
        return FIFTEENTH;
      case 1597:
        return SIXTEENTH;
      case 2584:
        return SEVENTEENTH;
      case 4181:
        return EIGHTEENTH;
      case 6765:
        return NINTEENTH;
      case 10946:
        return TWENTIETH;
      default:
        return null;
    }
  }
}
