java_library(
    name = "converter-main",
    srcs = glob(["**/*.java"]),
    deps = [
        "//core",
        "//core-streams",
        "//messageio",
        "//thrift",
        "//reflect",
        "//tools/java/net/morimekta/console",
        "//third-party:args4j",
        "//third-party:ini4j",
        "//third-party:slf4j-simple",
    ],
    visibility = ['//visibility:public'],
)
