java_library(
    name = "data-generator-main",
    srcs = glob(["*.java"]),
    deps = [
        "//prividence-internal:providence-idl",
        "//providence-core",
        "//providence-thrift",
        "//providence-tools/java/net/morimekta/console",
        "//providence-tools/java/net/morimekta/providence/tools/data",
        "//third-party:args4j_args4j",
        "//third-party:org_slf4j_slf4j_simple",
        "//third-party:org_apache_thrift_libthrift",
    ],
    visibility = ['//visibility:public'],
)
