java_library(
    name = "data-generator-main",
    srcs = glob(["*.java"]),
    deps = [
        "//providence-internal:providence-idl",
        "//providence-core",
        "//providence-thrift",
        "//providence-tools/java/net/morimekta/providence/tools/data",
        "//third-party:net_morimekta_utils_console_util",
        "//third-party:net_morimekta_utils_io_util",
        "//third-party:args4j_args4j",
        "//third-party:org_slf4j_slf4j_simple",
        "//third-party:org_apache_thrift_libthrift",
    ],
    visibility = ['//visibility:public'],
)
