java_library(
    name = "speed-test-main",
    srcs = glob(["*.java"]),
    deps = [
        "//testing:thrift-idl",
        "//testing:providence-idl",
        "//core",
        "//thrift",
        "//tools/java/net/morimekta/console",
        "//third-party:android-util",
        "//third-party:args4j",
        "//third-party:commons-math3",
        "//third-party:libthrift",
        "//third-party:slf4j-simple",
    ],
    visibility = ['//visibility:public'],
)
