java_library(
    name = "speed-test-main",
    srcs = glob(["*.java"]),
    deps = [
        "//providence-internal:thrift-idl",
        "//providence-internal:providence-idl",
        "//providence-core",
        "//providence-thrift",
        "//providence-tools/java/net/morimekta/console",
        "//third-party:android-util",
        "//third-party:args4j",
        "//third-party:commons-math3",
        "//third-party:libthrift",
        "//third-party:slf4j-simple",
    ],
    visibility = ['//visibility:public'],
)
