java_library(
    name = "speed-test-main",
    srcs = glob(["*.java"]),
    deps = [
        "//providence-internal:thrift-idl",
        "//providence-internal:providence-idl",
        "//providence-core",
        "//providence-thrift",
        "//third-party:net_morimekta_utils_android_util",
        "//third-party:net_morimekta_utils_console_util",
        "//third-party:args4j_args4j",
        "//third-party:org_apache_commons_commons_math3",
        "//third-party:org_apache_thrift_libthrift",
        "//third-party:org_slf4j_slf4j_simple",
    ],
    visibility = ['//visibility:public'],
)
