java_library(
  name = "converter",
  srcs = glob(["src/**/*.java"]),
  deps = [
    "//core:core",
    "//protocol:protocol",
    "//reflect:reflect",
    "//third-party/args4j:args4j",
    "//third-party/thrift:libthrift",
    "//utils:utils",
  ],
)

java_binary(
  name = "convert",
  deps = [
    ":converter",
  ],
  main_class = "org.apache.thrift.j2.converter.Convert",
  visibility = [
    "PUBLIC"
  ],
)
