java_library(
  name = "utils-console",
  srcs = glob(["java/**/console/*.java"]),
  deps = [
    "//third-party:args4j",
  ],
  visibility = ['//visibility:public'],
)

java_library(
  name = "utils-core",
  srcs = glob([
      "java/**/util/**/*.java",
      "java/**/util/*.java",
  ]),
  deps = [
    "//third-party:args4j",
  ],
  visibility = ['//visibility:public'],
)
