java_library(
    name = "converter-main",
    srcs = glob(["**/*.java"]),
    deps = [
        "//providence-core",
        "//providence-core-streams",
        "//providence-messageio",
        "//providence-thrift",
        "//providence-reflect",
        "//third-party:net_morimekta_utils_io_util",
        "//third-party:net_morimekta_utils_console_util",
        "//third-party:args4j_args4j",
        "//third-party:org_ini4j_ini4j",
        "//third-party:org_slf4j_slf4j_simple",
    ],
    visibility = ['//visibility:public'],
)
