/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package net.morimekta.test.thrift.thrift.number;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class numberConstants {

  public static final Imaginary kSqrtMinusOne = new Imaginary();
  static {
    kSqrtMinusOne.setV(0);
    kSqrtMinusOne.setI(-1);
  }

}
