java_library(
    name = "data",
    srcs = glob(["**/*.java"]),
    deps = [
        "//core",
        "//testing:providence-idl",
        "//third-party:commons-math3",
    ],
    visibility = ['//visibility:public'],
)
