java_library(
    name = "data",
    srcs = glob(["**/*.java"]),
    deps = [
        "//providence-core",
        "//providence-internal:providence-idl",
        "//third-party:net_morimekta_utils_io_util",
        "//third-party:org_apache_commons_commons_math3",
    ],
    visibility = ['//visibility:public'],
)
