genrule(
  name = 'mvn_fetch_init',
  cmd = 'mvn org.apache.maven.plugins:maven-dependency-plugin:2.1:get ' +
        '-Dartifact=junit:junit:4.12 ' +
        '-DrepoUrl=http://repo1.maven.org/maven2 > $OUT',
  out = 'mvn_fetch_init.out',
)

python_binary(
  name = 'mvn_fetch',
  main = 'mvn_fetch.py',
  visibility = ['PUBLIC'],
  deps = [
    ':mvn_fetch_init',
  ]
)
