genrule(
  name = 'mvn_fetch_init',
  cmd = 'mvn dependency:get -Dartifact=org.apache.maven.plugins:maven-dependency-plugin:2.1 > $OUT',
  out = 'mvn_fetch_init.out',
)

python_binary(
  name = 'mvn_fetch',
  main = 'mvn_fetch.py',
  visibility = ['PUBLIC'],
  deps = [
    ':mvn_fetch_init',
  ]
)
