java_library(
    name = "data-generator-main",
    srcs = glob(["*.java"]),
    deps = [
        "//testing:providence-idl",
        "//core:core",
        "//thrift",
        "//tools/java/net/morimekta/console",
        "//tools/java/net/morimekta/providence/tools/data",
        "//third-party:args4j",
        "//third-party:slf4j-simple",
        "//third-party:libthrift",
    ],
    visibility = ['//visibility:public'],
)
