java_library(
  name = "reflect",
  srcs = glob([
    "src/**/*.java",
    "model/**/*.java",
  ]),
  deps = [
    "//core:core",
  ],
  visibility = [ "PUBLIC" ],
)

java_test(
  name = "test",
  srcs = glob(["test/**/*.java"]),
  deps = [
    ":reflect",
    "//core:core",
    "//third-party/junit:junit",
  ],
)
