java_library(
  name = "jax-rs",
  srcs = glob(["src/**/*.java"]),
  deps = [
    "//core:core",
    "//third-party/javax-ws-rs:javax-ws-rs-api"
  ],
  visibility = [ "PUBLIC" ],
)

java_test(
  name = "test",
  srcs = glob(["test/**/*.java"]),
  deps = [
    ":jax-rs",
    "//core:core",
    "//core:generated",
    "//third-party/junit:junit",
    "//third-party/javax-ws-rs:javax-ws-rs-api"
  ],
)
